version: '3.3'

services:

  service-routing:
    build:
      context: service-routing
    volumes:
      - ./logs:/logs
      - ./graph-cache:/graph-cache
      - ./conf-routing:/conf
      - ./datasource-routing:/datasource
    command: server conf/config.yml
    ports:
      - 8989:8989

  nginx:
    image: nginx:1.18.0-alpine
    volumes: 
      - ./conf-nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./conf-nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1000:80